workspace:
  base: /go

pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  latest:
    image: docker
    storage_driver: overlay
    repo: plugins/npm
    tags: [ "latest", "1.0", "1" ]
    when:
      branch: master
      event: push

  develop:
    image: docker
    storage_driver: overlay
    repo: plugins/npm
    tags: [ "develop" ]
    when:
      branch: develop
      event: push

plugin:
  name: NPM
  desc: Publish files and artifacts to a NPM registry
  type: publish
  image: plugins/drone-node
  labels:
    - publish
    - node
